
parents: [origin]

device: cuda
seed: 0
num_workers: 0

checkpoint.freq: 10000
print.freq: 100
viz.freq: 500
records.freq: 100

dataset:

  name: mnist

  labeled: False

  batch_size: 128

  split.val: 0.1666666


model:
  _type: model

  nonlin: elu

  generator:
    _type: model

  discriminator:
    _type: model

  optim._type: adam

