_meta.script_name: train

parents: [default/wgan-gp]
#parents: [translation/cifar, default/cycle-gan]


#model._model_type: gan





###


name: test-pycharm

output.log_freq: 50

output.viz_freq: 100
inline: True
