_meta.script_name: train

parents: [default/dcgan]
#parents: [translation/cifar, default/cycle-gan]


#model._model_type: gan

name: test-pycharm

records.freq: 50
viz.freq: 100

inline: True

#model.generator.optim.lr: 0.0001


